type = "service_account"
project_id = "newregistration-469910"
private_key_id = "0592507ffaf67702f45cfe46e0ac63e948fc69ac"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcxLi0COTYICgD
42vtUSJVvai/Uffio7kmGu8fH87NanQJ+RKPJpLHJ7NXUnBXBznmxmh7QyW6Q+V9
i0rROyjXHaONm3vVGmIM5f4mIMN5tr/UrRQN5O9L6v2FYMVY5gqVatO8Zho0JYbt
3Fa8TeVkWtxNy3v9a6VBxe4xAoFwycjqMuGWmeFZ9JpvTk7LKulaZrd2S9cYQUN0
wJuStjfoasi5cFjWWpougfv77lMIiPzTj00cHP6b0b83xDLpJJE1zmagyDb+Czrg
G+8ePwjdGrmsuwVQbRo34QhBBzVU82ttEISOrzS4azx/Knc5cX0S24f65swyc7ft
rbiij7hJAgMBAAECggEAErUi17K3Pa8/5NB1OVd6OtzG+2tlP5HTIyz+HVuTKSn/
qkaucW352yF8m4YzWdSVbf5bJTLT9BxDyqcukFtcgxoSXXITBMRnEaO9rRpyphI7
4DhIbkL7minQEOjZ4EYiGHZEef8G8mtJq0dUHEHXkfD3ISqAl8Fy8AdnP0Twlg+D
BaeCdkrkW23IGqDL6AnZr3qvm6MFutZDyW1UQrpEVSPcxXsTVlmCQlIyffm2EALy
eVljciQV3xyLII3L/omet1QGWqJaXGVpYkgu6uYAsWkK/BIc23NGBoHBiQgZXgl2
JMF8AfjxhUnFhl12qcNA+iBeq0hN9ywhtXvwdoVE3wKBgQD0y4w9w4JnW/GLfkBQ
aVHZc26dFSXGTScOK6t5M5B31fhDwJeoWRvY8V/hyhJSmMUNSKseBB6UvaFOtRcQ
F5IIGahxPQ+rKTMSR+/Wcpr7QTn4VQEX+5mIQPh4kyiHHnHb+fRuFw1Taotl8FoG
5yqzzm8lNilIgmK7ZrcPvryJpwKBgQDm36KCRmkD7EIYNhbvVtGhUr//uHNUlegY
TfyOTijQHj08PPY++otFXF2w/kpbNud6KnCJMGaXohsKGfKChhVNHfU/pQIAiaXC
9uvxcCgAc8M8I9bs6eAQR9GgQse6lW2F2fgqf5wAxx6EA8k5J+TjVzcJs7Vpto/C
QVO7bD0MjwKBgQDkF1k4H5i9SA175Yp1onzSed0iXpcQ+8idSpF+4E4Hawbl0mk9
QrJQ5S9rCkciURiitQhEcqAwBbVsyg2QP/YguA+cW8HiwQPGT+Mo1SaVYIRsYIAh
YZ0AOVGLv8qug+6hgnh/r9kJ1afHtzmbXwAKBBrJ+HplBqCKbz25XQb91wKBgQDJ
EEwj7pP4gaISGdEhgVexijKBzy5JpP/rYsenWzQ6A4vK0UCXGnV943II+XziMU+o
WhuFrqw6NEgeJPjJaWJVtdhnJBo5Q6cjww06SDXeJvMJhiDgVNH4+8L5Mg9lVEt8
vZZd1KKVHtRZnj55U2AICWV6QpKkTQSn5WK5oAsOywKBgGh7TmqEHMtU9k/CMOv7
+9bQyNXa2/jqegkbsIU2Osu/c4v9zlK4dMSmfA6Xe0QCZlhm3xc+LfEYJUfY5uLD
lTMZWFLUPqCIRkL2fFvPDCcl0UY+h61pWmjp0p/iFTfXayNfBAsTSTN+nckpPmHI
fgUuu3GjDNl4AGlRddGT35p0
-----END PRIVATE KEY-----"""
client_email = "spark22@newregistration-469910.iam.gserviceaccount.com"
client_id = "114720780565192677068"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/spark22%40newregistration-469910.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
